---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elastic
  labels:
    k8s-app: elasticsearch
data:
  elasticsearch.yml: |-
    node.name: "elasticsearch-master1"
    cluster.name: "test-cluster"
    network.host: 0.0.0.0
    node.roles: [master, data, ingest]
    discovery.seed_hosts:
      - elasticsearch:9200
    cluster.initial_master_nodes:
      - elasticsearch-master1
    # node.voting_only: false
    # node.ml: true
    # xpack.ml.enabled: true
    # cluster.remote.connect: false
    # xpack.monitoring.collection.enabled: true # use metricbeat instead
    xpack.security.enabled: true
    xpack.license.self_generated.type: trial
    # xpack.security.http.ssl.enabled: true
    # xpack.security.http.ssl.keystore.path: "/usr/share/elasticsearch/config/http.p12"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  selector:
    matchLabels:
      name: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-master1
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        env:
        - name: ES_JAVA_OPTS
          value: -Xmx256m -Xms256m
        # - name: discovery.type
        #   value: single-node
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTIC_PASSWORD
          value: changeme
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          readOnly: true
          subPath: elasticsearch.yml
        # - name: http-cert
        #   mountPath: /usr/share/elasticsearch/config/http.p12
        #   readOnly: true
        #   subPath: http.p12
        # - name: http-cert
        #   mountPath: /usr/share/elasticsearch/config/ca.p12
        #   readOnly: true
        #   subPath: ca.p12
      volumes:
        ##### Requires setting permissions on host, for this to work
        ### chmod 775 or chown rihards:
      - name: elasticsearch-data
        hostPath:
          path: "/data/elasticsearch_data"
      - name: config
        configMap:
          defaultMode: 0777
          name: elasticsearch-config
      # - name: http-cert
      #   secret:
      #     secretName: http-cert
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: "htz1"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: cluster-comms
      port: 9300
      targetPort: 9300
      protocol: TCP
  selector:
    name: elasticsearch
