---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
        env:
        - name: ES_JAVA_OPTS
          value: -Xmx256m -Xms256m
        - name: discovery.type
          value: single-node
      #   volumeMounts:
      #   - mountPath: /usr/share/elasticsearch/data
      #     name: elasticsearch-data
      # volumes:
      #     ##### Requires setting permissions on host, for this to work
      #   - name: elasticsearch-data
      #     hostPath:
      #       path: "/data/elasticsearch_data"
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: "htz1"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    name: elasticsearch
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch
  namespace: elastic
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: mon2.rudenspavasaris.id.lv
    http:
      paths:
      - path: /
        backend:
          serviceName: elasticsearch
          servicePort: http
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  entryPoints:
    - https
  routes:
  - match: Host(`mon2.rudenspavasaris.id.lv`)
    kind: Rule
    services:
    - name: elasticsearch
      port: 9200
  tls:
    certResolver: default
