---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elastic
  labels:
    k8s-app: elasticsearch
data:
  elasticsearch.yml: |-
    node.name: "elasticsearch-master1"
    cluster.name: "test-cluster"
    network.host: 0.0.0.0
    node.master: true
    node.data: true
    node.ingest: false
    discovery.seed_hosts:
      - elasticsearch:9200
    cluster.initial_master_nodes:
      - elasticsearch-master1
    # node.voting_only: false
    # node.ml: true
    # xpack.ml.enabled: true
    # cluster.remote.connect: false
    # xpack.monitoring.collection.enabled: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  selector:
    matchLabels:
      name: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      containers:
      - name: elasticsearch-master1
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
        env:
        - name: ES_JAVA_OPTS
          value: -Xmx256m -Xms256m
        # - name: discovery.type
        #   value: single-node
        - name: xpack.security.enabled
          value: "true"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTIC_PASSWORD
          value: changeme
        - name: xpack.license.self_generated.type
          value: basic
      #   volumeMounts:
      #   - mountPath: /usr/share/elasticsearch/data
      #     name: elasticsearch-data
      # volumes:
      #     ##### Requires setting permissions on host, for this to work
      #   - name: elasticsearch-data
      #     hostPath:
      #       path: "/data/elasticsearch_data"
        volumeMounts:
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          readOnly: true
          subPath: elasticsearch.yml
      volumes:
      - name: config
        configMap:
          defaultMode: 0777
          name: elasticsearch-config
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: "htz1"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: cluster-comms
      port: 9300
      targetPort: 9300
      protocol: TCP
  selector:
    name: elasticsearch
