---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.1.1
        env:
        - name: ES_JAVA_OPTS
          value: -Xmx256m -Xms256m
        - name: discovery.type
          value: single-node
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: "htz1"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    name: elasticsearch
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: elasticsearch
#   annotations:
#     kubernetes.io/ingress.class: traefik
#     traefik.frontend.rule.type: PathPrefixStrip
# spec:
#   rules:
#   - host: mon1.rudenspavasaris.id.lv
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: elasticsearch
#           servicePort: http
