---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-ingest-config
  namespace: elastic
  labels:
    k8s-app: es-ingest
data:
  elasticsearch.yml: |-
    node.name: "elasticsearch-ingest1"
    cluster.name: "test-cluster"
    network.host: 0.0.0.0
    node.master: false
    node.data: false
    node.ingest: true
    discovery.seed_hosts:
      - elasticsearch:9300
    cluster.initial_master_nodes:
      - elasticsearch-master1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-ingest
  namespace: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      name: es-ingest
  template:
    metadata:
      labels:
        name: es-ingest
    spec:
      containers:
      - name: elasticsearch-ingest1
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        env:
        - name: ES_JAVA_OPTS
          value: -Xmx256m -Xms256m
        # - name: discovery.type
        #   value: single-node
        # - name: xpack.security.enabled
        #   value: "true"
        # - name: ELASTICSEARCH_USERNAME
        #   value: elastic
        # - name: ELASTIC_PASSWORD
        #   value: changeme
        - name: xpack.license.self_generated.type
          value: basic
      #   volumeMounts:
      #   - mountPath: /usr/share/elasticsearch/data
      #     name: elasticsearch-data
      # volumes:
      #     ##### Requires setting permissions on host, for this to work
      #   - name: elasticsearch-data
      #     hostPath:
      #       path: "/data/elasticsearch_data"
        volumeMounts:
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          readOnly: true
          subPath: elasticsearch.yml
      volumes:
      - name: config
        configMap:
          defaultMode: 0777
          name: es-ingest-config
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: "htz1"
---
apiVersion: v1
kind: Service
metadata:
  name: es-ingest
  namespace: elastic
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    name: es-ingest
