# https://www.elastic.co/guide/en/kibana/current/docker.html
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.2.0
        env:
          - name: SERVER_NAME
            value: mon.rudenspavasaris.id.lv
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic
  labels:
    name: kibana
spec:
  ports:
    - name: http
      port: 5601
      targetPort: 5601
  selector:
    name: kibana
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: kibana
#   annotations:
#     kubernetes.io/ingress.class: traefik
#     traefik.frontend.rule.type: PathPrefixStrip
# spec:
#   rules:
#   - host: mon.rudenspavasaris.id.lv
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: kibana
#           servicePort: http
