# https://www.elastic.co/guide/en/kibana/current/docker.html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: kibana
  template:
    metadata:
      labels:
        name: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.9.2
        env:
          - name: SERVER_NAME
            value: mon.rudenspavasaris.id.lv
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          readOnly: true
          subPath: kibana.yml
        # - name: elasticsearch-ca
        #   mountPath: /usr/share/kibana/config/elasticsearch-ca.pem
        #   readOnly: true
        #   subPath: elasticsearch-ca.pem
      volumes:
      - name: config
        configMap:
          defaultMode: 0666
          name: kibana-config
      # - name: elasticsearch-ca
      #   secret:
      #     secretName: elasticsearch-ca
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: "htz1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elastic
data:
  kibana.yml: |-
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    xpack.security.enabled: true
    elasticsearch.username: "elastic"
    elasticsearch.password: "changeme"
    # elasticsearch.ssl.certificateAuthorities: [ "config/elasticsearch-ca.pem" ]
    xpack.encryptedSavedObjects.encryptionKey: "pwpHw89wqzSAXBtMGMKJy4RLfwq3IVbsbTQDlBBdvkW8uvkIQaDnhA7UKFVTJDZ"
