---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-pub-config
  labels:
    app: netdata-pub
data:
  netdata.conf: |-
    [plugins]
      cgroups = yes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netdata-pub
  labels:
    app: netdata-pub
spec:
  selector:
    matchLabels:
      app: netdata-pub
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: netdata-pub
    spec:
      containers:
      - name: netdata
        image: netdata/netdata
        securityContext:
          capabilities:
            add: ["SYS_PTRACE"]
        volumeMounts:
        - name: proc
          mountPath: "/host/proc"
          readOnly: true
        - name: sys
          mountPath: "/host/sys"
          readOnly: true
        - name: docker-sock
          mountPath: "/var/run/docker.sock"
          readOnly: true
        - name: config
          mountPath: /etc/netdata/netdata.conf
          readOnly: true
          subPath: netdata.conf
      volumes:
      - name: proc
        hostPath:
          path: "/proc"
      - name: sys
        hostPath:
          path: "/sys"
      - name: docker-sock
        hostPath:
          path: "/var/run/docker.sock"
      - name: config
        configMap:
          name: netdata-pub-config
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: "htz1"
      tolerations:
      - key: "master"
        operator: "Exists"
---
apiVersion: v1
kind: Service
metadata:
  name: netdata-pub
spec:
  ports:
    - name: tcp
      port: 19999
      targetPort: 19999
      protocol: TCP
  selector:
    app: netdata-pub
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: netdata-pub
spec:
  entryPoints:
    - https
  routes:
  - match: Host(`netdata.rudenspavasaris.id.lv`)
    kind: Rule
    services:
    - name: netdata-pub
      port: 19999
  tls:
    certResolver: default
# ---
# # Ingres is setup for Keycloak gatekeeper instead
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: netdata-pub
#   annotations:
#     kubernetes.io/ingress.class: traefik
#     traefik.frontend.rule.type: PathPrefixStrip
# spec:
#   rules:
#   - host: mon0.rudenspavasaris.id.lv
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: netdata-pub
#           servicePort: tcp
