---
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-conf
  # namespace: kube-system
data:
  traefik.toml: |
    [api]
      dashboard = true
      insecure = true
    [accessLog]
    # [experimental]
      # http3 = true
      # http3 shall be available in 2.5. This experimental likely only works from master release
    [entryPoints]
      [entryPoints.http]
        # enableHTTP3 = true
        address = ":80"
        [entryPoints.http.http]
          [entryPoints.http.http.redirections]
            [entryPoints.http.http.redirections.entryPoint]
              to = "https"
              scheme = "https"
      [entryPoints.https]
        # enableHTTP3 = true
        address = ":443"
      [entryPoints.minecraft-tcp]
        address = ":25565"
      [entryPoints.minecraft-udp]
        address = ":25565/udp"
    [certificatesResolvers]
      [certificatesResolvers.default]
        [certificatesResolvers.default.acme]
          email = "rihards.teteris@outlook.com"
          storage = "/acme/acme.json"
          [certificatesResolvers.default.acme.httpChallenge]
            entryPoint = "http"
          [certificatesResolvers.default.acme.tlsChallenge]
    [providers.kubernetesCRD]
    [tls.options]
      [tls.options.default]
        cipherSuites = [
          "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        ]
        minVersion = "VersionTLS12"
      [tls.options.mintls13]
        minVersion = "VersionTLS13"
    [log]
      # level = "DEBUG"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strict-transport-security-header
spec:
  headers:
    stsSeconds: 15552000
    stsIncludeSubdomains: true
