apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller


---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
      - name: traefik
        image: traefik:v2.9.10
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /acme
          name: acme
        args:
        - --configfile=/config/traefik.toml
        ports:
        - name: acme
          containerPort: 81
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: gitlah-ssh
          containerPort: 4022
        - name: minecraft
          containerPort: 25565
        - name: admin
          containerPort: 8080
      volumes:
      - name: config
        configMap:
          name: traefik-conf
      - name: acme
        hostPath:
          path: /acme
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: htz1
