---
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-conf
  # namespace: kube-system
data:
  traefik.toml: |
    [serversTransport]
      insecureSkipVerify = true
    [api]
      dashboard = true
      insecure = true
    [accessLog]
    [experimental]
      http3 = true
    [entryPoints]
      [entryPoints.acme]
        address = ":81"
      [entryPoints.http]
        address = ":80"
        # [entryPoints.http.http]
        #   [entryPoints.http.http.redirections]
        #     [entryPoints.http.http.redirections.entryPoint]
        #       to = "https"
        #       scheme = "https"
      [entryPoints.https]
        address = ":443"
      [entryPoints.https.http3]
        advertisedPort = 443
      [entryPoints.gitlab-ssh]
        address = ":4022"
      [entryPoints.minecraft-tcp]
        address = ":25565"
      [entryPoints.minecraft-udp]
        address = ":25565/udp"
    [certificatesResolvers]
      [certificatesResolvers.default]
        [certificatesResolvers.default.acme]
          email = "rihards.teteris@outlook.com"
          storage = "/acme/acme.json"
          [certificatesResolvers.default.acme.httpChallenge]
            entryPoint = "acme"
          [certificatesResolvers.default.acme.tlsChallenge]
    [providers.kubernetesCRD]
    [log]
      # level = "DEBUG"

    [backends]
      [backends.acme]
        [backends.acme.servers]
          [backends.acme.servers.server0]
            url = "http://127.0.0.1:81/"
    [frontends]
      [frontends.acme]
        entryPoints = ["http"]
        backend = "acme"
        passHostHeader = true
        priority = 1000
        [frontends.acme.routes]
          [frontends.acme.routes.route0]
            rule = "PathPrefix:/.well-known/acme-challenge/"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strict-transport-security-header
spec:
  headers:
    stsSeconds: 15552000
    stsIncludeSubdomains: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: mintls13
  namespace: default
spec:
  minVersion: VersionTLS13
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: default
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
