---
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-conf
  # namespace: kube-system
data:
  traefik.toml: |
    [api]
      dashboard = true
      insecure = true
    [accessLog]
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        [entryPoints.http.http]
          [entryPoints.http.http.redirections]
            [entryPoints.http.http.redirections.entryPoint]
              to = "https"
              scheme = "https"
      [entryPoints.https]
        address = ":443"
      [entryPoints.minecraft-tcp]
        address = ":25565"
      [entryPoints.minecraft-udp]
        address = ":25565/udp"
    [certificatesResolvers]
      [certificatesResolvers.default]
        [certificatesResolvers.default.acme]
          email = "rihards.teteris@outlook.com"
          storage = "/acme/acme.json"
          [certificatesResolvers.default.acme.httpChallenge]
            entryPoint = "http"
          [certificatesResolvers.default.acme.tlsChallenge]
    [providers.kubernetesCRD]
    [log]
      # level = "DEBUG"
