---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runner
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-files
  namespace: gitlab-runner
data:
  file1.yaml: |-
    file1 contents
  file2.yaml: |-
    file2 contents
