image:
  repository: sonarqube
resources:
  limits:
    cpu: 800m
    memory: 3Gi
  requests:
    cpu: 100m
    memory: 100Mi
plugins:
  install:
    # - URL
  netrcCreds: sonarqube-netrc
  jvmOpts: "-Djdk.xml.xpathExprGrpLimit=0 -Djdk.xml.xpathExprOpLimit=0 -Djdk.xml.xpathTotalOpLimit=0"
  jvmCeOpts: "-Djdk.xml.xpathExprGrpLimit=0 -Djdk.xml.xpathExprOpLimit=0 -Djdk.xml.xpathTotalOpLimit=0"
persistence:
  volumes:
    - name: jaxp
      configMap:
        defaultMode: 0666
        name: sonarqube-jaxp-properties
  mounts:
    - name: jaxp
      mountPath: /opt/java/openjdk/conf/jaxp.properties
      readOnly: true
      subPath: jaxp.properties
