---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
# Add annotation to set the storage class as default
# kubectl patch storageclass local-storage -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
# mkdir /data/elasticsearch_data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/elasticsearch_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - htz1
