---
apiVersion: v1
kind: Namespace
metadata:
  name: github-arc
---
apiVersion: v1
kind: Secret
metadata:
  name: github-arc-token-template
  namespace: github-arc
type: Opaque
data:
  # github_token: BASE64_TOKEN

# `echo "TOKEN" | base64` gave different value than `kubectl create secret`
# This can recommend creating token manually beforehand with:
# kubectl create secret generic github-arc-token -n github-arc --from-literal=github_token='TOKEN'
# Then you can do this, to copy the correct value to local secrets_token file
# kubectl edit secret github-arc-token -n github-arc
