# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    k8s-app: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    rule_files:
      # - "first.rules"
      # - "second.rules"
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']
      - job_name: elasticsearch-exporter
        scrape_interval: 15s
        static_configs:
          - targets: ['mon3.rudenspavasaris.id.lv:443']
        metrics_path: /metrics
        scheme: https
      - job_name: elastic-to-prometheus
        scrape_interval: 30s
        static_configs:
          - targets: ['rudenspavasaris.id.lv:8092']
        metrics_path: /metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      name: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.31.1
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/prometheus.yml
          readOnly: true
          subPath: prometheus.yml
      volumes:
      - name: config
        configMap:
          defaultMode: 0777
          name: prometheus-config
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: "htz1"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    name: prometheus
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
spec:
  entryPoints:
    - https
  routes:
  - match: Host(`pr.rudenspavasaris.id.lv`)
    kind: Rule
    services:
    - name: prometheus
      port: 9090
  tls:
    certResolver: default
