---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
data:
  admin_password: BASE64_ENCODED_PASSWORD_GOES_HERE
  postgres_password: BASE64_ENCODED_PASSWORD_GOES_HERE
  # tls.key:
  # tls.crt:
