kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
          entryPoint = "https"

      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]

    [kubernetes]
    [acme]
      email = "rihards.teteris@outlook.com"
      storage = "/acme/acme.json"
      entryPoint = "https"
      acmeLogging = true
    [acme.tlsChallenge]
    [[acme.domains]]
      main = "rudenspavasaris.id.lv"
      sans = ["vieta.rudenspavasaris.id.lv", "doks.rudenspavasaris.id.lv", "mon.rudenspavasaris.id.lv"]
    [[acme.domains]]
      main = "mon0.rudenspavasaris.id.lv"
      sans = ["mon1.rudenspavasaris.id.lv", "mon2.rudenspavasaris.id.lv","mon3.rudenspavasaris.id.lv"]
