apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:15.0.5-apache
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: POSTGRES_DB
          value: nextcloud
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          value: "PASSWORD_GOES_HERE"
          # valueFrom:
          #   secretKeyRef:
          #     name: nextcloud-password
          #     key: .env_nc
        - name: POSTGRES_HOST
          value: "postgres:5432"
        - name: NEXTCLOUD_ADMIN_USER
          value: rihards
        - name: NEXTCLOUD_ADMIN_PASSWORD
          value: "PASSWORD_GOES_HERE"
          # valueFrom:
          #   secretKeyRef:
          #     name: nextcloud-password
          #     key: .env
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "vieta.rudenspavasaris.id.lv"
        - name: NEXTCLOUD_URL
          value: "vieta.rudenspavasaris.id.lv"
        volumeMounts:
        - mountPath: /var/www/html
          name: nextcloud-data
      restartPolicy: Always
      volumes:
        - name: nextcloud-data
          hostPath:
            path: "/data/nextcloud_data"
      nodeSelector:
        kubernetes.io/hostname: "back-xs"
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: nextcloud
