apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        ports:
        - containerPort: 443
          protocol: TCP
        - containerPort: 4422
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/gitlab
          name: gitlab-config
        - mountPath: /var/log/gitlab
          name: gitlab-logs
        - mountPath: /var/opt/gitlab
          name: gitlab-data
      restartPolicy: Always
      volumes:
        - name: gitlab-config
          hostPath:
            path: "/data/gitlab_data/config"
        - name: gitlab-logs
          hostPath:
            path: "/data/gitlab_data/logs"
        - name: gitlab-data
          hostPath:
            path: "/data/gitlab_data/data"
      nodeSelector:
        kubernetes.io/hostname: "gitlab"
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  ports:
  - name: https
    targetPort: 443
    port: 443
  - name: ssh
    targetPort: 4422
    port: 4422
  selector:
    app: gitlab

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gitlab
spec:
  entryPoints:
    - https
  routes:
  - match: HostSNI(`gitlab.rudenspavasaris.id.lv`)
    kind: Rule
    services:
    - name: gitlab
      port: 443
    # - name: gitlab
    #   port: 4422
  tls:
    passthrough: true
