---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-configmap
  labels:
    k8s-app: gitlab
data:
  gitlab.rb: |-
    ##! Check out the latest version of this file to know about the different
    ##! settings that can be configured, when they were introduced and why:
    ##! https://gitlab.com/gitlab-org/omnibus-gitlab/blame/master/files/gitlab-config-template/gitlab.rb.template

    external_url "https://gitlab.rudenspavasaris.id.lv"

    gitlab_rails['gitlab_ssh_host'] = 'gitlab-ssh.rudenspavasaris.id.lv'
    gitlab_rails['gitlab_shell_ssh_port'] = 4022

    # Need to generate wildcard cert first I guess. Eh
    pages_external_url "http://pages.rudenspavasaris.id.lv"
    # pages_external_url "https://pages.rudenspavasaris.id.lv"
    # pages_nginx['redirect_http_to_https'] = true
    # pages_nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.rudenspavasaris.id.lv.crt"
    # pages_nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.rudenspavasaris.id.lv.key"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:14.4.1-ce.0
        volumeMounts:
        - name: config
          mountPath: /etc/gitlab/gitlab.rb
          readOnly: true
          subPath: gitlab.rb
        - mountPath: /etc/gitlab
          name: gitlab-config
        - mountPath: /var/log/gitlab
          name: gitlab-logs
        - mountPath: /var/opt/gitlab
          name: gitlab-data
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            defaultMode: 0600
            name: gitlab-configmap
        - name: gitlab-config
          hostPath:
            path: "/data/gitlab/config"
        - name: gitlab-logs
          hostPath:
            path: "/data/gitlab/logs"
        - name: gitlab-data
          hostPath:
            path: "/data/gitlab/data"
      nodeSelector:
        kubernetes.io/hostname: "htz1"
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  ports:
  - name: https
    targetPort: 443
    port: 443
  - name: http
    targetPort: 80
    port: 80
  - name: ssh
    targetPort: 22
    port: 22
  selector:
    app: gitlab
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gitlab
spec:
  entryPoints:
    - https
  routes:
  - match: HostSNI(`gitlab.rudenspavasaris.id.lv`)
    kind: Rule
    services:
    - name: gitlab
      port: 443
  tls:
    passthrough: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gitlab-ssh
spec:
  entryPoints:
    - gitlab-ssh # uses port 4022
  routes:
  - match: HostSNI(`*`)
    services:
    - name: gitlab
      port: 22
--- # http ingress should only be for acme challenge
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-http
spec:
  entryPoints:
    - http
  routes:
  - match: Host(`gitlab.rudenspavasaris.id.lv`)
    priority: 1001
    kind: Rule
    services:
    - name: gitlab
      port: 80
--- # Dirty test with http Gitlab pages
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab-http-pages
spec:
  entryPoints:
    - http
  routes:
  - match: HostRegexp(`{subdomain:[a-z]+}.pages.rudenspavasaris.id.lv`) # or {subdomain:.*}
    priority: 1001
    kind: Rule
    services:
    - name: gitlab
      port: 80
