---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radicale-config
  labels:
    k8s-app: radicale
data:
  config: |-
    [auth]
    type = htpasswd
    htpasswd_filename = /etc/radicale/users
    htpasswd_encryption = plain
    [storage]
    filesystem_folder = /etc/radicale/collections
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radicale-pv
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/radicale
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - oc1pub
          - htz1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-pvc
  labels:
    k8s-app: radicale
spec:
  storageClassName:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radicale
  labels:
    app: radicale
spec:
  selector:
    matchLabels:
      app: radicale
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radicale
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      initContainers:
      - name: init-permissions
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /etc/radicale/collections"]
        volumeMounts:
          - name: radicale-data
            mountPath: /etc/radicale/collections
      containers:
      - name: radicale
        image: registry.gitlab.com/rudenspavasaris/cloud_project_terraform_oracle/radicale:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5232
          protocol: TCP
        volumeMounts:
        - name: radicale-config
          mountPath: /etc/radicale/config
          subPath: config
        - name: radicale-users
          mountPath: /etc/radicale/users
          subPath: users
        - name: radicale-data
          mountPath: /etc/radicale/collections
      volumes:
        - name: radicale-config
          configMap:
            defaultMode: 0777
            name: radicale-config
        - name: radicale-users
          secret:
            secretName: radicale-users
        - name: radicale-data
          persistentVolumeClaim:
            claimName: radicale-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: radicale
spec:
  ports:
  - name: http
    targetPort: 5232
    port: 5232
  selector:
    app: radicale
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radicale
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rad.oc1.rudenspavasaris.id.lv`)
      kind: Rule
      services:
        - name: radicale
          port: http
  tls:
    certResolver: letsencrypt
