---
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  hosts:
  - ssh:
      address: 207.127.93.236
      user: ubuntu
      port: 22
      keyPath: null
    role: controller
    installFlags:
    - --kubelet-extra-args=--node-ip=207.127.93.236
  - ssh:
      address: 129.151.200.81
      user: ubuntu
      port: 22
      keyPath: null
    role: worker
    installFlags:
    - --kubelet-extra-args=--node-ip=129.151.200.81
  options:
    wait:
      enabled: true
    drain:
      enabled: true
      gracePeriod: 2m0s
      timeout: 5m0s
      force: true
      ignoreDaemonSets: true
      deleteEmptyDirData: true
      podSelector: ""
      skipWaitForDeleteTimeout: 0s
    concurrency:
      limit: 30
      workerDisruptionPercent: 10
      uploads: 5
    evictTaint:
      enabled: false
      taint: k0sctl.k0sproject.io/evict=true
      effect: NoExecute
      controllerWorkers: false
# Had to do all this, just to change default metricsPort, as Traefik wants 8080
# Based on https://github.com/k0sproject/k0sctl/blob/main/README.md#configuration-file
  k0s:
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s-cluster
      spec:
        network:
          kuberouter:
            metricsPort: 8082
