# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
# https://prometheus.io/docs/instrumenting/exporters/

---
apiVersion: v1
kind: Namespace
metadata:
  name: mon

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    k8s-app: prometheus
    namespace: mon
data:
  prometheus.yaml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    rule_files:
      # - "first.rules"
      # - "second.rules"
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']
      - job_name: node
        static_configs:
        - targets: ['rudenspavasaris.id.lv:9100']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: mon
spec:
  selector:
    matchLabels:
      name: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.49.1
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/prometheus.yaml
          readOnly: true
          subPath: prometheus.yaml
      volumes:
      - name: config
        configMap:
          defaultMode: 0777
          name: prometheus-config
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: "htz1"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: mon
spec:
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    name: prometheus
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: mon
spec:
  entryPoints:
    - https
  routes:
  - match: Host(`pr.rudenspavasaris.id.lv`)
    kind: Rule
    services:
    - name: prometheus
      port: 9090
  tls:
    certResolver: default
