# https://www.elastic.co/guide/en/apm-server/current/docker.html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  namespace: elastic
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: apm-server
  template:
    metadata:
      labels:
        name: apm-server
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 0
      containers:
      - name: apm-server
        image: docker.elastic.co/apm/apm-server:8.11.1
        # command: ["apm-server", "-e",
        #   "-E", "output.elasticsearch.hosts=['https://elasticsearch:9200']"
        # ]
        volumeMounts:
        - name: config
          mountPath: /usr/share/apm-server/apm-server.yml
          readOnly: true
          subPath: apm-server.yml
        - name: elasticsearch-ca
          mountPath: /usr/share/apm-server/elasticsearch-ca.pem
          readOnly: true
          subPath: elasticsearch-ca.pem
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: apm-config
      - name: elasticsearch-ca
        secret:
          secretName: elasticsearch-ca
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: "htz1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-config
  namespace: elastic
data:
  # https://github.com/elastic/apm-server/blob/main/apm-server.yml
  apm-server.yml: |-
    apm-server:
      host: "0.0.0.0:8200"
      rum:
        enabled: true
        event_rate.limit: 300
        event_rate.lru_size: 1000
        allow_origins: ['*']
    output.elasticsearch:
      hosts: https://elasticsearch:9200
      username: "elastic"
      password: "changeme"
      ssl.certificate_authorities: ["/usr/share/apm-server/elasticsearch-ca.pem"]
      # index: "apm-%{+YYYY.MM.DD}"
    queue.mem.events: 4096
    max_procs: 4
    monitoring:
      enabled: true
---
apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: elastic
  labels:
    name: apm-server
spec:
  ports:
    - name: http
      port: 8200
      targetPort: 8200
  selector:
    name: apm-server
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: apm-server
  namespace: elastic
spec:
  entryPoints:
    - https
  routes:
  - match: Host(`apm.rudenspavasaris.id.lv`)
    kind: Rule
    services:
    - name: apm-server
      port: 8200
  tls:
    certResolver: default
