---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - image: itzg/minecraft-server
        name: minecraft
        env:
        - name: EULA
          value: "true"
        - name: MEMORY
          value: "1400M"
        ports:
        - containerPort: 25565
          name: main
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
      volumes:
      - name: minecraft-data
        hostPath:
          path: "/data/minecraft_data"
      nodeSelector:
        kubernetes.io/hostname: "htz1"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: minecraft-node
# spec:
#   type: NodePort
#   ports:
#   - port: 25565
#     nodePort: 30000
#   selector:
#     app: minecraft
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  ports:
  - name: minecraft
    targetPort: 25565
    port: 25565
  selector:
    app: minecraft
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: minecraft
spec:
  entryPoints:
    - minecraft-tcp
  routes:
  - match: HostSNI(`*`)
    services:
    - name: minecraft
      port: 25565
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: minecraft
spec:
  entryPoints:
    - minecraft-udp
  routes:
  - services:
    - name: minecraft
      port: 25565
