---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic
---
apiVersion: v1
kind: Secret
metadata:
  name: http-cert
  namespace: elastic
type: Opaque
data:
  # ca.p12 could be unused? Need to double check that
  ca.p12: |-
    base64_thing_here
  http.p12: |-
    base64_thing_here
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-ca
  namespace: elastic
type: Opaque
data:
  elasticsearch-ca.pem: |-
    base64_thing_here
