---
apiVersion: v1
kind: Pod
metadata:
  name: dind
  namespace: default
spec:
  containers:
  - name: dind
    ### With root
    # image: docker:dind
    # securityContext:
    #   privileged: true
    ## Rootless
    image: docker:dind-rootless
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    volumeMounts:
    - name: docker-graph-storage
      mountPath: /var/lib/docker
  volumes:
  - name: docker-graph-storage
    emptyDir: {}
